import { useState } from "react";
import FolderSelector from "./FolderSelector";
import PrimaryButton from "./PrimaryButton";


export default function ProjectForm(){

  const [projectName,setProjectName] = useState("");

  const [folder,setFolder] = useState("");


  async function handleGenerate(){

    if(!projectName.trim()){

      alert("Informe o nome do projeto");
      return;

    }


    if(!folder){

      alert("Selecione uma pasta");
      return;

    }


    const destination =
      `${folder}/${projectName}`;


    const result =
      await window.api.generator.generateProject({

        template:"express-js",

        destination,

        variables:{

          PROJECT_NAME:projectName,

          DESCRIPTION:
          "API generated by API Bootstrap",

          AUTHOR:"Pietro",

          YEAR:
          String(new Date().getFullYear())

        }

      });


    console.log(result);


    if(result.success){

      alert("Projeto criado com sucesso");

    }
    else{

      alert(result.message);

    }

  }



  return (

    <div
      style={{
        display:"flex",
        flexDirection:"column",
        gap:20,
        width:400
      }}
    >


      <div>

        <label>
          Nome do projeto
        </label>

        <input

          value={projectName}

          onChange={
            e=>setProjectName(e.target.value)
          }

          placeholder="Minha API"

          style={{
            width:"100%",
            padding:8
          }}

        />

      </div>



      <FolderSelector

        folder={folder}

        setFolder={setFolder}

      />



      <PrimaryButton

        onClick={handleGenerate}

      >

        Criar Projeto

      </PrimaryButton>


    </div>

  );

}